# Generated by Django 3.2.8 on 2021-11-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(db_index=True, default='Anonymous', max_length=50, verbose_name='Description'),
        ),
    ]
